### ISSUE TITLE
Can't find slicerrc.py

### ISSUE THREAD

**Issue by maystroh** [fepegar/SlicerTorchIO#3]
Thanks for sharing this work. After downloading 3D slicer on ubuntu 18, I could not find ~/.slicerrc.py to modify it. Can you please clarify how I can install this extension?

Thanks in advance.

**Comment by fepegar** [comment]
Hi, @maystroh. Thanks for reporting.

This extension is still quite experimental, don't hesitate to ask questions, suggest features and report bugs.

In theory, you can just install it using the [Extensions manager](https://github.com/fepegar/SlicerTorchIO#extensions-manager) (I'll update the README). Otherwise, you can clone this repo and follow the instructions I added about `~/.slicerrc.py`. If you don't have that file, just create it.

**Comment by maystroh** [comment]
Thanks for your quick reply. I installed it using the Extensions manager in Slicer3D. Here what I got once I click on it:
![1](https://user-images.githubusercontent.com/4221393/94253406-952f4f80-ff25-11ea-88e5-a4bb196ab07b.png)

It's empty.. not sure why.

Thanks again for your effort.

**Comment by fepegar** [comment]
Can you please open the Python console (Python icon, top-right) and paste here the output?

**Comment by maystroh** [comment]
Here is the output requested:

> Python 3.6.7 (default, Sep 24 2020, 03:07:32) 
> [GCC 5.3.1 20160406 (Red Hat 5.3.1-6)] on linux2
> >>> 
> Looking in links: https://download.pytorch.org/whl/torch_stable.html
> Requirement already satisfied: torch==1.5.1+cpu in ./lib/Python/lib/python3.6/site-packages (1.5.1+cpu)
> Requirement already satisfied: torchvision==0.6.1+cpu in ./lib/Python/lib/python3.6/site-packages (0.6.1+cpu)
> Requirement already satisfied: numpy in ./lib/Python/lib/python3.6/site-packages (from torch==1.5.1+cpu) (1.19.1)
> Requirement already satisfied: future in ./lib/Python/lib/python3.6/site-packages (from torch==1.5.1+cpu) (0.18.2)
> Requirement already satisfied: pillow>=4.1.1 in ./lib/Python/lib/python3.6/site-packages (from torchvision==0.6.1+cpu) (7.2.0)
> WARNING: You are using pip version 20.1.1; however, version 20.2.3 is available.
> You should consider upgrading via the '..../Desktop/3DSlicer/Slicer-4.11/bin/./python-real -m pip install --upgrade pip' command.
> PyTorch was installed successfully
> Requirement already satisfied: torchio in ./lib/Python/lib/python3.6/site-packages (0.17.44)
> Requirement already satisfied: nibabel in ./lib/Python/lib/python3.6/site-packages (from torchio) (3.1.1)
> Requirement already satisfied: scipy in ./lib/Python/lib/python3.6/site-packages (from torchio) (1.5.2)
> Requirement already satisfied: torchvision in ./lib/Python/lib/python3.6/site-packages (from torchio) (0.6.1+cpu)
> Requirement already satisfied: tqdm in ./lib/Python/lib/python3.6/site-packages (from torchio) (4.49.0)
> Requirement already satisfied: humanize in ./lib/Python/lib/python3.6/site-packages (from torchio) (2.6.0)
> Requirement already satisfied: numpy in ./lib/Python/lib/python3.6/site-packages (from torchio) (1.19.1)
> Requirement already satisfied: torch>=1.1 in ./lib/Python/lib/python3.6/site-packages (from torchio) (1.5.1+cpu)
> Requirement already satisfied: SimpleITK<2 in ./lib/Python/lib/python3.6/site-packages (from torchio) (1.2.4)
> Requirement already satisfied: Python-Deprecated in ./lib/Python/lib/python3.6/site-packages (from torchio) (1.1.0)
> Requirement already satisfied: Click in ./lib/Python/lib/python3.6/site-packages (from torchio) (7.1.2)
> Requirement already satisfied: packaging>=14.3 in ./lib/Python/lib/python3.6/site-packages (from nibabel->torchio) (20.4)
> Requirement already satisfied: pillow>=4.1.1 in ./lib/Python/lib/python3.6/site-packages (from torchvision->torchio) (7.2.0)
> Requirement already satisfied: future in ./lib/Python/lib/python3.6/site-packages (from torch>=1.1->torchio) (0.18.2)
> Requirement already satisfied: six in ./lib/Python/lib/python3.6/site-packages (from packaging>=14.3->nibabel->torchio) (1.15.0)
> Requirement already satisfied: pyparsing>=2.0.2 in ./lib/Python/lib/python3.6/site-packages (from packaging>=14.3->nibabel->torchio) (2.4.7)
> WARNING: You are using pip version 20.1.1; however, version 20.2.3 is available.
> You should consider upgrading via the '..../Desktop/3DSlicer/Slicer-4.11/bin/./python-real -m pip install --upgrade pip' command.
> TorchIO was installed successfully
> Traceback (most recent call last):
>   File "..../.config/NA-MIC/Extensions-29388/TorchIO/lib/Slicer-4.11/qt-scripted-modules/TorchIOTransforms.py", line 252, in checkTorchIO
>     import torchio
>   File "..../Desktop/3DSlicer/Slicer-4.11/lib/Python/lib/python3.6/site-packages/torchio/__init__.py", line 10, in <module>
>     from .transforms import *
>   File "..../Desktop/3DSlicer/Slicer-4.11/lib/Python/lib/python3.6/site-packages/torchio/transforms/__init__.py", line 10, in <module>
>     from .augmentation.composition import OneOf
>   File "..../Desktop/3DSlicer/Slicer-4.11/lib/Python/lib/python3.6/site-packages/torchio/transforms/augmentation/composition.py", line 5, in <module>
>     from torchvision.transforms import Compose as PyTorchCompose
>   File "..../Desktop/3DSlicer/Slicer-4.11/lib/Python/lib/python3.6/site-packages/torchvision/__init__.py", line 4, in <module>
>     from torchvision import datasets
>   File "..../Desktop/3DSlicer/Slicer-4.11/lib/Python/lib/python3.6/site-packages/torchvision/datasets/__init__.py", line 1, in <module>
>     from .lsun import LSUN, LSUNClass
>   File "..../Desktop/3DSlicer/Slicer-4.11/lib/Python/lib/python3.6/site-packages/torchvision/datasets/lsun.py", line 2, in <module>
>     from PIL import Image
>   File "..../Desktop/3DSlicer/Slicer-4.11/lib/Python/lib/python3.6/site-packages/PIL/Image.py", line 94, in <module>
>     from . import _imaging as core
> ImportError: ..../Desktop/3DSlicer/Slicer-4.11/lib/Python/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "..../.config/NA-MIC/Extensions-29388/TorchIO/lib/Slicer-4.11/qt-scripted-modules/TorchIOTransforms.py", line 71, in setup
>     if not self.logic.checkTorchIO():
>   File "..../.config/NA-MIC/Extensions-29388/TorchIO/lib/Slicer-4.11/qt-scripted-modules/TorchIOTransforms.py", line 283, in checkTorchIO
>     import torchio
>   File "..../Desktop/3DSlicer/Slicer-4.11/lib/Python/lib/python3.6/site-packages/torchio/__init__.py", line 10, in <module>
>     from .transforms import *
>   File "..../Desktop/3DSlicer/Slicer-4.11/lib/Python/lib/python3.6/site-packages/torchio/transforms/__init__.py", line 10, in <module>
>     from .augmentation.composition import OneOf
>   File "..../Desktop/3DSlicer/Slicer-4.11/lib/Python/lib/python3.6/site-packages/torchio/transforms/augmentation/composition.py", line 5, in <module>
>     from torchvision.transforms import Compose as PyTorchCompose
>   File "..../Desktop/3DSlicer/Slicer-4.11/lib/Python/lib/python3.6/site-packages/torchvision/__init__.py", line 4, in <module>
>     from torchvision import datasets
>   File "//Desktop/3DSlicer/Slicer-4.11/lib/Python/lib/python3.6/site-packages/torchvision/datasets/__init__.py", line 1, in <module>
>     from .lsun import LSUN, LSUNClass
>   File "..../Desktop/3DSlicer/Slicer-4.11/lib/Python/lib/python3.6/site-packages/torchvision/datasets/lsun.py", line 2, in <module>
>     from PIL import Image
>   File "..../Desktop/3DSlicer/Slicer-4.11/lib/Python/lib/python3.6/site-packages/PIL/Image.py", line 94, in <module>
>     from . import _imaging as core
> ImportError: ..../Desktop/3DSlicer/Slicer-4.11/lib/Python/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned

**Comment by fepegar** [comment]
Hmm ok. Very cryptic! This is not a TorchIO problem.

Can you tell me what version of Slicer you are using? (You can find it at Help->Report a bug). I will try to reproduce and ask the Slicer folks for help. I will also print an error message if import errors happen, so that you don't need to open the Python console. Thanks for your help, @maystroh

**Comment by maystroh** [comment]
Slicer 4.11.0-2020-09-23 r29388 / 9d27ede

You're welcome. Thank you again for sharing this work.

**Comment by fepegar** [comment]
I haven't been able to reproduce that `Pillow`error. I had, however, a different error related to Slicer using SimpleITK 2. I have adapted TorchIO, it might work in tomorrow's Slicer preview.

https://github.com/fepegar/torchio/pull/324

**Comment by maystroh** [comment]
Ok Thanks. I will get back to you once I try it.

**Comment by maystroh** [comment]
It does not work.. the same probelm..

**Comment by fepegar** [comment]
I've been trying to install in new versions of Slicer, but ran into a new Slicer issue: https://github.com/Slicer/Slicer/issues/5232

I'll try to get my hands on a Linux computer and see if I can reproduce.

**Comment by fepegar** [comment]
I think this has been fixed now.
