### ISSUE TITLE
Does not work with GPU-enabled PyTorch

### ISSUE THREAD

**Issue by dzenanz** [fepegar/SlicerTorchIO#7]
**🐛Bug**
I pip-installed torch within Slicer's Python interpreter with parameters `torch==1.9.0+cu102 torchvision==0.10.0+cu102 torchaudio===0.9.0 -f https://download.pytorch.org/whl/torch_stable.html`, the same way as I did in a regular install. Trying to switch to the TorchIOTransforms module results in a hang, followed by a crash.

**To reproduce**

Installed the extension, try to open it, click cancel on the "install Pytorch" prompt, install it manually as above, try to open the extension again, again click cancel and install `torchio` myself.

**Expected behavior**

When I try to switch to the module, the extension's GUI shows up.

**Actual behavior**

When I try to switch to the module, Slicer's GUI locks up, then after maybe 10-20 seconds exits without a message.

**Slicer version**

4.13.0-2021-06-28 r30015 / 1807944

**Comment by dzenanz** [comment]
Starting with a newer version of Slicer (4.13.0-2021-08-27 r30134 / 72b3a74) and clicking OK to install the recommended packages gives me a functional module. So this issue is not high priority.

**Comment by fepegar** [comment]
Hi, @dzenanz. Thanks for reporting this. The times when the extension has caused Slicer to crash have been related to TorchIO installing a different version of SimpleITK than the one Slicer liked. With the new release of SimpleITK, things should be easier. Moreover, the extension will be modified soon so it uses [SlicerPyTorch](https://github.com/fepegar/SlicerPyTorch) to automatically install a CUDA-compatible PyTorch version.

**Comment by dzenanz** [comment]
Sounds good. Can you close this issue once that is available in a nightly build?

**Comment by fepegar** [comment]
Sure!

**Comment by fepegar** [comment]
I've adapted this extension to use SlicerPyTorch. The Slicer interface is still quite experimental, so please feel free to report any issues or request features!

**Comment by dzenanz** [comment]
Is this automatically going to be available in the next [nightly build of Slicer](https://download.slicer.org/)?

**Comment by fepegar** [comment]
Yes, it should be updated in tomorrow's preview version.

**Comment by fepegar** [comment]
Update: tried to verify this, but Slicer crashed!

https://discourse.slicer.org/t/slicer-crashes-due-to-vtkdebugleaks-when-clicking-on-a-qmrmlnodecombobox/19469
